### PR TITLE
Bump version to 0.11.2

### PR DESCRIPTION
**Pull request by OscarWang114**
Bumping to a new version so the web interface could start using the latest functionalities.

Requires #483 to be merged first.

### CODE REVIEW

**Review by odashi — APPROVED** [review]
Let's go ahead.

FYI: there is an issue discussing about versioning. We may apply some other practices from the next version. #485

**Comment by pfliu-nlp** [comment]
@OscarWang114  
Feel free to go ahead since https://github.com/neulab/ExplainaBoard/pull/483 has been merged.
Also, one very important thing is that there are usually some potential incompatible issues in the ExplainaBoard web due to the upgrade of Explainaboard SDK. So it would be nice if you can perform some lightweight usability tests on some tasks after you upgrade the SDK version number in explainaboard_web repo.

Here is one example of the usability test: https://github.com/neulab/explainaboard_web/issues/311
You don't need to test all, maybe select some typical tasks first.

**Comment by neubig** [comment]
@pfliu-nlp : FYI, we have a checklist here https://github.com/neulab/explainaboard_web/wiki/Pre-release-Checklist

You can add things to it if you'd like. It might be nice to also automate some of these things if possible.

**Comment by pfliu-nlp** [comment]
Aha interesting and thanks for the pointer, I will refine it later.

**Comment by OscarWang114** [comment]
Just finished class, thanks for merging the PR! 

The checklist is definitely helpful. I'll use it to check the next release and see if there's anything I'd like to add as well.

**Pull request merged**
