### PR TITLE
Remove additional config argument from Metric

### PR DESCRIPTION
**Pull request by odashi**
This change removes `config` arguments from methods in `Metric`.

Overall, this argument is rarely utilized while it is not referred appropriately in many subclasses. Since we can instantiate another `Metric` object to use different configs, I thought that we can remove this argument without any drawbacks.

This pull request also contains some typing errors in `Metric` classes.

### CODE REVIEW

**Review by pfliu-nlp — APPROVED** [review]
This is pretty straightforward and looks good, I approved.

**Review by neubig — APPROVED** [review]
I approve.

Just to clarify, the reason why this was implemented this way in the first place was because we were assuming that there may be some evaluation metrics (e.g. embedding-based metrics) where the initialization cost is high, but metrics with different configurations (e.g. different languages to be evaluated) could be run with the same initialization. However, this has become unimportant given how we use EB now (basically we re-start the program every time we evaluate a new system).

**Comment by odashi** [comment]
@neubig I think we should implement some inner singleton to hold sharable objects in the same metric instead of overriding the config.

**Comment by neubig** [comment]
Sounds good, I'd suggest we revisit that if when it becomes necessary.

**Pull request merged**
