### PR TITLE
Split bucket interval

### LINKED ISSUE #431: `bucket_interval` is type-ambiguous
Currently `bucket_interval` is ambiguous in its typing, which is basically `tuple[float,float] | type[str,]` where the former is used for continuous values and latter is used for discrete values. 
https://github.com/neulab/ExplainaBoard/blame/main/explainaboard/analysis/performance.py#L11

We should probably change to the following:
```
bucket_interval: tuple[float,float] | None
bucket_name: str | None
```

### PR DESCRIPTION
**Pull request by odashi**
This pull request splits bucket intervals into two variables: interval ([float, float]) and name (str).

Fixes #431.

### CODE REVIEW

**Comment by odashi** [comment]
@neubig Could you fix an error around draw_charts.py? It looks a bug but I couldn't guess the correct fix.

**Comment by neubig** [comment]
@odashi done!

**Review by neubig — APPROVED** [review]
LGTM, thanks!

**Comment by odashi** [comment]
@neubig Thanks. It looks the change contains a cornercase so I will fix a bit before merging.

**Pull request merged**
