### PR TITLE
Added functionality in processor to sort by bucket performance

### PR DESCRIPTION
**Pull request by hwidjaja**

### CODE REVIEW

**Comment by pfliu-nlp** [comment]
hi, @hwidjaja thanks for the PR. the implementation looks good and it would be nice if you can fix some formatting issues to pass the above checks.

**Comment by lyuyangh** [comment]
just fyi, if you run
```
pip install ."[dev]"
pre-commit install
```
it will install several pre-commit hooks which will auto-fix the formatting issues  and give you error messages for the other checks when you make a commit.

**Comment by hwidjaja** [comment]
Are you guys getting this error while doing the commit hooks?

[INFO] Installing environment for https://github.com/sondrelg/pep585-upgrade.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\haris\\.cache\\pre-commit\\repo6y2b8tr2\\py_env-python3.7\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing c:\users\haris\.cache\pre-commit\repo6y2b8tr2
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'done'

stderr:
    ERROR: Package 'pep585-upgrade' requires a different Python: 3.7.3 not in '<4.0,>=3.8'

Check the log at C:\Users\haris\.cache\pre-commit\pre-commit.log

My python version is 3.9.7 so not sure what it means when "3.7.3 not in '<4.0,>=3.8'"

**Comment by lyuyangh** [comment]
hmmm, I haven't seen this before. Looks like pre-commit is trying to use the python here `C:\Users\haris\.cache\pre-commit\repo6y2b8tr2\py_env-python3.7\Scripts\python.EXE`. Is that the python executable you use for this repo or do you use another python version? I don't have a windows machine to reproduce this but I'm guessing one possible issue is that you are running git in a different environment so it's actually using another python executable?

**Comment by pfliu-nlp** [comment]
@hwidjaja thanks for the PR.
I have two comments:
(1)  could you add two unitttest scripts for bucket sorting and kg task generalization
(2) I saw we have re-format the system output file of kg task, the current format is:
```
{
    "user_defined_features_configs": {
        "rel_type": {
                "dtype": "string",
                "description": "symmetric or asymmetric",
                "num_buckets": 2
        }
    },
    "predictions": {
        "1": {
            "gold_head": "/m/08966",
            "gold_predicate": "/travel/travel_destination/climate./travel/travel_destination_monthly_climate/month",
            "gold_tail": "/m/05lf_",
            "predict": "tail",
            "predictions": [
                "/m/05lf_",
                "/m/02x_y",
                "/m/01nv4h",
                "/m/02l6h",
                "/m/0kz1h"
            ],
            "rel_type": "asymmetric"
        },
}
```
I'm rethinking the "predictions" part,
is it possible to modify it from
```
predictions:{
{"1":{"gold_head":"/m/08966"}},
{"2":{"gold_head":"/m/08966"}},
}
```
to
{
```
predictions:[
{"gold_head":"/m/08966"}
]
```
}
The reason why I suggest this is because other tasks follow a similar format, if KG could also have this, then the data loader for KG could be unified.
But, if we have some reason for the current format, that's fine.

**Comment by hwidjaja** [comment]
@pfliu-nlp We can definitely talk about this. For now, I'm still using the old format but just checking that everything still works. Updated the tests to adhere to the new system output format.

**Review by pfliu-nlp — APPROVED** [review]

**Pull request merged**
