### PR TITLE
Add text-to-sql evaluation metrics

### PR DESCRIPTION
**Pull request by shuaichenchang**
Add text-to-sql evaluation metrics

# Overview

This PR is the first of three PRs to add text-to-sql evaluation metrics.
1. Add exact set match accuracy and execution accuracy metrics, and test files
2. Add loader and integration test
3. Add processors

# Details

This PR adds metrics in `explainaboard/metrics`, and test functions in `integration_tests/metric_test.py`. 
The metrics use the code from `explainaboard/third_party/text_to_sql_test_suit_eval` for text-to-sql task evaluations.

### CODE REVIEW

**Comment by pfliu-nlp** [comment]
@shuaichenchang Regarding task-dependent PyPI libraries, maybe you can refer to [this](https://github.com/neulab/ExplainaBoard/pull/452/commits/377b4570efee5a64dfdf103d63569861adf97530) strategy to figure out a good way to introduce them?

**Comment by tetsuok** [comment]
@shuaichenchang The configurations of the failing CI jobs need to be updated to make CI green. Namely, the following places:
- https://github.com/neulab/ExplainaBoard/blob/main/.github/workflows/ci.yml#L24
- https://github.com/neulab/ExplainaBoard/blob/main/.github/workflows/ci.yml#L43

CI jobs (unit-tests and integration-tests) are failing because these jobs aren't configured to install required packages with the [extra](https://peps.python.org/pep-0508/#extras), `text_to_sql`. In other words, these jobs need to run `pip install ."[text_to_sql]"` to install required packages for text-to-sql, but they currently run `pip install .` instead.

**Comment by tetsuok** [comment]
@shuaichenchang Any update on this PR. Would you check my comment? Let me know if you have any questions.

**Comment by shuaichenchang** [comment]
It seems I accidentally added others' commits to my PR when I merge the main into my branch. Now the PR has too many commits. Do you know how to undo them or I may need to create a PR just for the commits I submitted? @pfliu-nlp @odashi Sorry for the inconvenience.

**Comment by odashi** [comment]
@shuaichenchang How about:

1. withdraw this pull request
2. `git checkout <your preferred commit>`, `git checkout -b <new tag>`
3. propose a new pull request on the new tag

**Comment by shuaichenchang** [comment]
> @shuaichenchang How about:
> 
> 1. withdraw this pull request
> 2. `git checkout <your preferred commit>` then `git checkout -b <new tag>`
> 3. propose a new pull request on the new tag

@odashi Sounds great! I picked my commits and created a new branch and PR.

**Pull request closed without merging**
