### PR TITLE
Bugfix: Missing Package Initializer in metrics/auxiliary

### LINKED ISSUE #439: ModuleNotFoundError: No module named 'explainaboard.metrics.auxiliary'
I encountered this error while running 
```
explainaboard --task qa-tat --output-file-type json --dataset tat_qa --system-outputs predictions_list.json > report.json
```

The traceback:
```
(eb-sdk) ➜  explainaBoard git:(main) ✗ explainaboard --task qa-tat --output-file-type json --dataset tat_qa --system-outputs predictions_list.json > report.json
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/eb-sdk/bin/explainaboard", line 5, in <module>
    from explainaboard.explainaboard_main import main
  File "/opt/homebrew/Caskroom/miniforge/base/envs/eb-sdk/lib/python3.9/site-packages/explainaboard/__init__.py", line 4, in <module>
    from explainaboard.processors import get_processor
  File "/opt/homebrew/Caskroom/miniforge/base/envs/eb-sdk/lib/python3.9/site-packages/explainaboard/processors/__init__.py", line 2, in <module>
    from explainaboard.processors import (
  File "/opt/homebrew/Caskroom/miniforge/base/envs/eb-sdk/lib/python3.9/site-packages/explainaboard/processors/qa_tat.py", line 16, in <module>
    from explainaboard.metrics.qa_table_text_hybrid import (
  File "/opt/homebrew/Caskroom/miniforge/base/envs/eb-sdk/lib/python3.9/site-packages/explainaboard/metrics/qa_table_text_hybrid.py", line 10, in <module>
    from explainaboard.metrics.auxiliary import qa_table_text_hybrid_auxiliary as eval_util
ModuleNotFoundError: No module named 'explainaboard.metrics.auxiliary'
```

### PR DESCRIPTION
**Pull request by noelchen90**
I added a `__init__.py` file to solve Issue #439 
Closes #439

### CODE REVIEW

**Comment by noelchen90** [comment]
@pfliu-nlp 
This pull request failed in the mypy test.
The code seems to has some errors in the line shown below which I am not familiar with https://github.com/neulab/ExplainaBoard/blob/main/explainaboard/metrics/qa_table_text_hybrid.py#L71
Could you check it please?

**Comment by noelchen90** [comment]
The error is
```
[INFO] Installing environment for https://github.com/python/black.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://gitlab.com/pycqa/flake8.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pycqa/isort.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/sondrelg/pep585-upgrade.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
black....................................................................Passed
flake8...................................................................Passed
isort....................................................................Passed
Upgrade type hints.......................................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

explainaboard/metrics/qa_table_text_hybrid.py:72: error: Argument 1 to "sample_level_metric" of "QATatMetric" has incompatible type "str"; expected "List[Any]"
explainaboard/metrics/qa_table_text_hybrid.py:72: error: Argument 2 to "sample_level_metric" of "QATatMetric" has incompatible type "str"; expected "List[Any]"
explainaboard/metrics/qa_table_text_hybrid.py:112: error: Incompatible types in assignment (expression has type "Tuple[List[str], List[Set[str]]]", variable has type "List[Any]")
explainaboard/metrics/qa_table_text_hybrid.py:113: error: Incompatible types in assignment (expression has type "Tuple[List[str], List[Set[str]]]", variable has type "List[Any]")
explainaboard/metrics/qa_table_text_hybrid.py:142: error: Incompatible types in assignment (expression has type "Tuple[List[str], List[Set[str]]]", variable has type "List[Any]")
explainaboard/metrics/qa_table_text_hybrid.py:143: error: Incompatible types in assignment (expression has type "Tuple[List[str], List[Set[str]]]", variable has type "List[Any]")
Found 6 errors in 1 file (checked 1 source file)
```

**Comment by pfliu-nlp** [comment]
I will take a look now. Thanks!

**Comment by pfliu-nlp** [comment]
@noelchen90 it should be fine now

**Review by neubig — APPROVED** [review]
This works, thanks!

**Pull request merged**
