### PR TITLE
Add docstring linter

### LINKED ISSUE #404: Consolidating docstring format
Docstrings are sometimes written and sometimes not in this repository. There are also multiple styles applied to each docstring (reST style, Google style, and something else). To avoid this confusion, we need to decide some writing policy about docstrings.
Specifically, I realized we need to discuss at least:

- when we have to add docstrings
- which style is applied
- how to check docstrings

### PR DESCRIPTION
**Pull request by odashi**
Fixes #404

Work-in-progress.

@neubig @pfliu-nlp There are too many errors. Could you fix several files directly in this branch?

### CODE REVIEW

**Comment by pfliu-nlp** [comment]
>"There are too many errors. Could you fix several files directly in this branch?"

Thanks, will try to follow this.

**Comment by neubig** [comment]
It took a while, but I fixed about 75% of the 1000-or-so linter errors, and I think the documentation is improved as a result! I'm done for tonight but let's try to wrap it up :)

**Comment by odashi** [comment]
@neubig Thanks for a bunch of effort for adding documentation!

Since this pull request affects almost the whole repository, merging this should precede other changes to avoid unnecessary cherry-picking.

**Review by odashi — COMMENTED** [review]
Great, thanks!
(I couldn't self-approve this pull request)

**Review by neubig — APPROVED** [review]

**Review by pfliu-nlp — APPROVED** [review]
I only have one comment for the future PR: we really need a doc to instruct developers on how to fix different types of CI errors including the docstring.

**Comment by neubig** [comment]
Good point @pfliu-nlp : I agree.

@odashi : go ahead and merge if you think it's ready.

**Pull request merged**
