### PR TITLE
Restructure test files

### PR DESCRIPTION
**Pull request by odashi**
Related to https://github.com/neulab/ExplainaBoard/issues/398

This PR attempts to change the whole structure of test codes.

- Separate integration tests from `explainaboard` directory. They are now placed on `integration_tests` top-level directory that are processed separately.
- Introduce separate test scripts for unit tests `cicd/run_unit_tests.sh` and integration tests `cicd/run_integration_tests.sh`
- Change test file names from `test_*.py` to `*_test.py`
- Change TestCase class names from `Test*` to `*Test` to follow the same naming convention.

CC: @tetsuok

### CODE REVIEW

**Review by lyuyangh — APPROVED** [review]
Thanks for making this massive change! I think this also has the added benefit of a smaller package because all the tests and artifacts are excluded when it's distributed.

**Review by neubig — APPROVED** [review]
Yes, this looks great to me and I agree with Lyuyang that it'll be good to reduce the distribution package size as well.

**Review by pfliu-nlp — APPROVED** [review]
Thanks, and it looks nice!

**Comment by odashi** [comment]
> Thanks for making this massive change! I think this also has the added benefit of a smaller package because all the tests and artifacts are excluded when it's distributed.

Yes this is also intended. To this end we also need to modify `setup.py`. At this moment we'll keep the current script since it is somewhat out of interest of this PR.

**Pull request merged**
